version: "3.7"
services:
  php:
    extends:
      file: ./docker/common-services.yaml
      service: php
    build:
      target: stable
    env_file:
      - ./.env
  nginx:
    extends:
      file: ./docker/common-services.yaml
      service: nginx
    build:
      target: stable
    env_file:
      - ./.env
networks:
  docker_app:
    driver: bridge
