version: "3.9"

services:
  php:
    env_file:
      - ./.env.local
    extends:
      file: ./docker/common-services.yaml
      service: php
    build:
      target: local
    environment:
      - HISTFILE=/root/.bash_history
    volumes:
      - ./app:/var/www/html
      - ./docker/php/bash_history:/root/.bash_history
  nginx:
    env_file:
      - ./.env.local
    extends:
      file: ./docker/common-services.yaml
      service: nginx
    build:
      target: local
    environment:
      - HISTFILE=/root/.bash_history
    volumes:
      - ./app/www:/var/www/html/www
      - ./docker/nginx/bash_history:/root/.bash_history
  otelcol:
    env_file:
      - ./.env.local
    extends:
      file: ./docker/common-services.yaml
      service: otelcol
    # command: [ "--config=/etc/otelcol-config-extras.yml" ]
    volumes:
      - ./docker/otelcol-config-extras.yml:/etc/otelcol-config-extras.yml
    ports:
      - "${OTEL_COLLECTOR_PORT_GRPC}"
      - "${OTEL_COLLECTOR_PORT_HTTP}"
networks:
  docker_app:
    driver: bridge
